language: cpp
os: linux
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      compiler: gcc 
      env: COVERALLS_SERVICE_NAME=travis-ci
    - os: linux
      compiler: gcc
      env: VALGRIND_TESTS=ON
    - os: osx
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - ninja-build
      - valgrind
      - g++-7
      - clang-5.0

install:
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then
        brew update && brew install ninja 
    else
        if [[ "${CXX}" = "clang++" ]]; then 
            export CXX="clang++-5.0"
            export CC="clang-5.0"
        else
            export CXX="g++-7"
            export CC="gcc-7"
        fi
    fi
  - ${CXX} --version
  - if [ -n "${COVERALLS_SERVICE_NAME}" ]; then gem install coveralls-lcov; fi
  - if [ -n "${COVERALLS_SERVICE_NAME}" ]; then wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz && tar xf lcov_1.13.orig.tar.gz && make -C lcov-1.13 "PREFIX=${HOME}/.local" install && export PATH="${PATH}:${HOME}/.local/bin"; fi
# we have to build lcov on our own as version 1.10 in apt is incompatible with coveralls gem; It is not possible to install lcov from deb as it doesn't recognize installed perl package.

script: ./travis.sh

after_success:
 - if [ -n "${COVERALLS_SERVICE_NAME}" ]; then
      lcov --rc lcov_branch_coverage=1 --directory build --capture --output-file coverage.info &&
      lcov --rc lcov_branch_coverage=1 --remove coverage.info
          "${PWD}/3rdparty/*"
          "${PWD}/build/*"
          "${PWD}/examples/*"
          "${PWD}/features/*"
          "${PWD}/tests/*"
          "/usr/*"
          --output-file coverage.info &&
      lcov --rc lcov_branch_coverage=1 --list coverage.info &&
      coveralls-lcov coverage.info ;
  fi

# default notifications: https://docs.travis-ci.com/user/notifications#Notifications
